// ./proto/orders/order.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: orders/order.proto

package orders

import (
	product "github.com/nguyenhoang711/example-go-grpc-gateway/protogen/golang/product"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,proto3" json:"order_id,omitempty"`
	CustomerId    uint64                 `protobuf:"varint,2,opt,name=customer_id,proto3" json:"customer_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,proto3" json:"is_active,omitempty"`
	Products      []*product.Product     `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	OrderDate     *date.Date             `protobuf:"bytes,5,opt,name=order_date,proto3" json:"order_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_orders_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_orders_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_orders_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetCustomerId() uint64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Order) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Order) GetProducts() []*product.Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *Order) GetOrderDate() *date.Date {
	if x != nil {
		return x.OrderDate
	}
	return nil
}

// A generic empty message that you can re-use to avoid defining duplicated
// empty messages in your APIs
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_orders_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_orders_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_orders_order_proto_rawDescGZIP(), []int{1}
}

type PayloadWithSingleOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadWithSingleOrder) Reset() {
	*x = PayloadWithSingleOrder{}
	mi := &file_orders_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadWithSingleOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadWithSingleOrder) ProtoMessage() {}

func (x *PayloadWithSingleOrder) ProtoReflect() protoreflect.Message {
	mi := &file_orders_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadWithSingleOrder.ProtoReflect.Descriptor instead.
func (*PayloadWithSingleOrder) Descriptor() ([]byte, []int) {
	return file_orders_order_proto_rawDescGZIP(), []int{2}
}

func (x *PayloadWithSingleOrder) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_orders_order_proto protoreflect.FileDescriptor

const file_orders_order_proto_rawDesc = "" +
	"\n" +
	"\x12orders/order.proto\x1a\x15product/product.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/date.proto\"\xbc\x01\n" +
	"\x05Order\x12\x1a\n" +
	"\border_id\x18\x01 \x01(\x04R\border_id\x12 \n" +
	"\vcustomer_id\x18\x02 \x01(\x04R\vcustomer_id\x12\x1c\n" +
	"\tis_active\x18\x03 \x01(\bR\tis_active\x12$\n" +
	"\bproducts\x18\x04 \x03(\v2\b.ProductR\bproducts\x121\n" +
	"\n" +
	"order_date\x18\x05 \x01(\v2\x11.google.type.DateR\n" +
	"order_date\"\a\n" +
	"\x05Empty\"6\n" +
	"\x16PayloadWithSingleOrder\x12\x1c\n" +
	"\x05order\x18\x01 \x01(\v2\x06.OrderR\x05order2L\n" +
	"\x06Orders\x12B\n" +
	"\bAddOrder\x12\x17.PayloadWithSingleOrder\x1a\x06.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v0/ordersBJZHgithub.com/nguyenhoang711/example-go-grpc-gateway/protogen/golang/ordersb\x06proto3"

var (
	file_orders_order_proto_rawDescOnce sync.Once
	file_orders_order_proto_rawDescData []byte
)

func file_orders_order_proto_rawDescGZIP() []byte {
	file_orders_order_proto_rawDescOnce.Do(func() {
		file_orders_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_order_proto_rawDesc), len(file_orders_order_proto_rawDesc)))
	})
	return file_orders_order_proto_rawDescData
}

var file_orders_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orders_order_proto_goTypes = []any{
	(*Order)(nil),                  // 0: Order
	(*Empty)(nil),                  // 1: Empty
	(*PayloadWithSingleOrder)(nil), // 2: PayloadWithSingleOrder
	(*product.Product)(nil),        // 3: Product
	(*date.Date)(nil),              // 4: google.type.Date
}
var file_orders_order_proto_depIdxs = []int32{
	3, // 0: Order.products:type_name -> Product
	4, // 1: Order.order_date:type_name -> google.type.Date
	0, // 2: PayloadWithSingleOrder.order:type_name -> Order
	2, // 3: Orders.AddOrder:input_type -> PayloadWithSingleOrder
	1, // 4: Orders.AddOrder:output_type -> Empty
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_orders_order_proto_init() }
func file_orders_order_proto_init() {
	if File_orders_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_order_proto_rawDesc), len(file_orders_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_order_proto_goTypes,
		DependencyIndexes: file_orders_order_proto_depIdxs,
		MessageInfos:      file_orders_order_proto_msgTypes,
	}.Build()
	File_orders_order_proto = out.File
	file_orders_order_proto_goTypes = nil
	file_orders_order_proto_depIdxs = nil
}
